x= input("Enter a number: ")
y= input("Enter another number: ")
z= int(x) + int(y)
z1=int(x) / int(y)
z2= round(z1,2)
print("The sum of", x, "and", y, "is", z)
print("The division of", x, "by", y, "is", z2)
