x= input("Enter a number: ")
y= input("Enter another number: ")
z0= int(x) + int(y)
z1= int(x) - int(y)
z2= int(x) * int(y)
print("The sum of the two numbers is: ", z0)
print("The difference of the two numbers is: ", z1)
print("The product of the two numbers is: ", z2)    